/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import cordinator.Cordinator;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Petar
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabelImeKorisnika = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOpis = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemDodajPozajmicu = new javax.swing.JMenuItem();
        jMenuItemPregledPozajmica = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemDodajClana = new javax.swing.JMenuItem();
        jMenuItemPregledClana = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDodajRadnika = new javax.swing.JMenuItem();
        jMenuItemPregledRadnika = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDodajKnjgu = new javax.swing.JMenuItem();
        jMenuItemPregledKnjiga = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemDodajTC = new javax.swing.JMenuItem();
        jMenuItemPregledTC = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemDodajTD = new javax.swing.JMenuItem();
        jMenuItemPregledTD = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Zdravo,");

        jMenu5.setText("Pozajmica");

        jMenuItemDodajPozajmicu.setText("Dodaj");
        jMenuItemDodajPozajmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajPozajmicuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDodajPozajmicu);

        jMenuItemPregledPozajmica.setText("Pregled");
        jMenuItemPregledPozajmica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledPozajmicaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPregledPozajmica);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Clan");

        jMenuItemDodajClana.setText("Dodaj");
        jMenuItemDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajClanaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemDodajClana);

        jMenuItemPregledClana.setText("Pregled");
        jMenuItemPregledClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledClanaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPregledClana);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("Radnik");

        jMenuItemDodajRadnika.setText("Dodaj");
        jMenuItemDodajRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajRadnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDodajRadnika);

        jMenuItemPregledRadnika.setText("Pregled");
        jMenuItemPregledRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledRadnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPregledRadnika);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Knjiga");

        jMenuItemDodajKnjgu.setText("Dodaj");
        jMenuItemDodajKnjgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajKnjguActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDodajKnjgu);

        jMenuItemPregledKnjiga.setText("Pregled");
        jMenuItemPregledKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledKnjigaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPregledKnjiga);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tip Clanstva");

        jMenuItemDodajTC.setText("Dodaj");
        jMenuItemDodajTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTCActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemDodajTC);

        jMenuItemPregledTC.setText("Pregled");
        jMenuItemPregledTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledTCActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPregledTC);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Termin Dezurstva");

        jMenuItemDodajTD.setText("Dodaj");
        jMenuItemDodajTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTDActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDodajTD);

        jMenuItemPregledTD.setText("Pregled");
        jMenuItemPregledTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledTDActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPregledTD);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImeKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImeKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPregledRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledRadnikaActionPerformed
        // TODO add your handling code here:'
        
        Cordinator.getInstance().otvoriPrikazRadnikaFormu();
        
    }//GEN-LAST:event_jMenuItemPregledRadnikaActionPerformed

    private void jMenuItemPregledClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledClanaActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriPrikazClanovaFormu();
        
    }//GEN-LAST:event_jMenuItemPregledClanaActionPerformed

    private void jMenuItemDodajRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajRadnikaActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriDodajRadnikaFormu();
        
    }//GEN-LAST:event_jMenuItemDodajRadnikaActionPerformed

    private void jMenuItemDodajKnjguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajKnjguActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriDodajKnjiguFormu();
        
    }//GEN-LAST:event_jMenuItemDodajKnjguActionPerformed

    private void jMenuItemPregledKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledKnjigaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazKnjigaFormu();
        
    }//GEN-LAST:event_jMenuItemPregledKnjigaActionPerformed

    private void jMenuItemDodajTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTCActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriDodajTipClanstvaFormu();
        
    }//GEN-LAST:event_jMenuItemDodajTCActionPerformed

    private void jMenuItemPregledTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledTCActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriPrikazTipClanstvaFormu();
        
    }//GEN-LAST:event_jMenuItemPregledTCActionPerformed

    private void jMenuItemDodajTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTDActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriDodajTerminDezurstvaFormu();
        
    }//GEN-LAST:event_jMenuItemDodajTDActionPerformed

    private void jMenuItemPregledTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledTDActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriPrikazTerminDezurstvaFormu();
        
    }//GEN-LAST:event_jMenuItemPregledTDActionPerformed

    private void jMenuItemDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajClanaActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriDodajClanaFormu();
        
    }//GEN-LAST:event_jMenuItemDodajClanaActionPerformed

    private void jMenuItemDodajPozajmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajPozajmicuActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Izaberite clana za kojeg cete kreirati pozajmicu","INFORMACIJA" , JOptionPane.INFORMATION_MESSAGE);
        
        Cordinator.getInstance().otvoriPrikazClanovaFormu();
        
    }//GEN-LAST:event_jMenuItemDodajPozajmicuActionPerformed

    private void jMenuItemPregledPozajmicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledPozajmicaActionPerformed
        // TODO add your handling code here:
        
        Cordinator.getInstance().otvoriPrikazPozajmicaFormu();
        
    }//GEN-LAST:event_jMenuItemPregledPozajmicaActionPerformed

    public JLabel getjLabelImeKorisnika() {
        return jLabelImeKorisnika;
    }

    public void setjLabelImeKorisnika(JLabel jLabelImeKorisnika) {
        this.jLabelImeKorisnika = jLabelImeKorisnika;
    }

    public JLabel getjLabelOpis() {
        return jLabelOpis;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImeKorisnika;
    private javax.swing.JLabel jLabelOpis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDodajClana;
    private javax.swing.JMenuItem jMenuItemDodajKnjgu;
    private javax.swing.JMenuItem jMenuItemDodajPozajmicu;
    private javax.swing.JMenuItem jMenuItemDodajRadnika;
    private javax.swing.JMenuItem jMenuItemDodajTC;
    private javax.swing.JMenuItem jMenuItemDodajTD;
    private javax.swing.JMenuItem jMenuItemPregledClana;
    private javax.swing.JMenuItem jMenuItemPregledKnjiga;
    private javax.swing.JMenuItem jMenuItemPregledPozajmica;
    private javax.swing.JMenuItem jMenuItemPregledRadnika;
    private javax.swing.JMenuItem jMenuItemPregledTC;
    private javax.swing.JMenuItem jMenuItemPregledTD;
    // End of variables declaration//GEN-END:variables
}
